spring.application.name=organizasenai
#spring.datasource.url=postgresql://dpg-d3r3m6pr0fns73frl7m0-a.oregon-postgres.render.com/projeto_integrador_2x2r
#postgresql://projeto_integrador_2x2r_user:8apJolD2QGNmM6BX7yjeXmv8Y7pD1HOv@dpg-d3r3m6pr0fns73frl7m0-a.oregon-postgres.render.com/projeto_integrador_2x2r
spring.datasource.url=jdbc:postgresql://dpg-d3r3m6pr0fns73frl7m0-a.oregon-postgres.render.com/projeto_integrador_2x2r
spring.datasource.username=projeto_integrador_2x2r_user
spring.datasource.password=8apJolD2QGNmM6BX7yjeXmv8Y7pD1HOv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true 